# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8018c5dee2ec488d24b2256436357547d0ecbc9f4c5551d4ca9532cb64e2cf6627bf09c60f18a7464c9e3d928da1c204da34339394c1ae796e9dd8a81a6684f1

test:
  secret_key_base: 8bc42455fad7f0e4615c602acad76183e24421ff10f24893418493a30fd271529d96f61161f509f09ad8c3b3755a70ee034b30706fa36d37153990d3e5dfcf58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
